### ISSUE TITLE
Jar in Maven repo

### ISSUE THREAD

**Issue by agrebnev** [simbiose/Encryption#6] opened 2015-03-16 18:30 UTC
Hi @ademar111190 

I can see that you published aar into Maven repo. However it looks like there are no something special for Android in your lib. It will be better to publish it as usual jar. Also it will be cool to remove android package dependencies.

Currently I cannot use your library in simple Java or Gradle/Groovy.

**Comment by ademar111190** [comment] 2015-03-20 14:15
It is a good Point. 

Currently the only Android dependency is the LogCat and AsyncTask booth simple replaced by normal java classes, so the next sprint I'll remove the android dependency and will look for jar instead aar format.

**Comment by ademar111190** [comment] 2015-05-17 03:57
Today I push the initial work at branch [development](https://github.com/simbiose/Encryption/tree/development) of the new version 1.3.0 that will works both in Android and Java. Now the java users can at least test the .jar version without android dependencies.

**Comment by ademar111190** [comment] 2016-02-01 00:05
Today I finished the "Java port" and I merged the development branch with the master, so I think that the issue is done. The unique reservation is the change of Maven to JitPack.io.

**Closed** 2016-02-01 00:07 UTC
